### ISSUE TITLE
[Question] Fork to Emacsmirror

### ISSUE THREAD

**Issue by jcs090218** [emacs-grammarly/keytar#1]
Hi @tarsius, I realized you have forked this repository to Emacsmirror. I am just wondering the reason to fork this package. Does Emacsmirror apply to CELPA too? Or I have made this package to one of the dependency to `lsp-grammarly`?, etc. I am just curious about the principle of Emacsmirror.

Thanks! :)

*P.S. I don't know where to open this issue so I just opened it in my own repo.*

**Comment by tarsius** [comment]
The Emacsmirror is a mirror of "all" Emacs packages. It provides not only a list of available packages and some metadata, but it also provides copies of all package repositories as a "backup". Among other things that allows us to move the repositories of obsolete packages to the Emacsattic sister project, without risking not being able to do so because upstream deleted the only public repository.

You can learn more about the Emacsmirror at https://emacsmirror.net.

**Comment by jcs090218** [comment]
Thanks for the response! ❤️
